# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - super-gradients
      - pycocotools
      - ultralytics
      - opencv-python
      - ipykernel
